### ISSUE TITLE
Minor edits/suggestions/comments

### ISSUE THREAD

**Issue by davidlmobley** [jalemkul/gmx_tutorials_livecoms#2]
Grammar/typo issues:
- p4 first column, "can be download"
- p15 column 2, in "Second, one cannot say that a simulation ..." should the dash be a long dash?
- p33 column 2, "as a random process, even versions of the ..." I don't think the software versioning is a random process. Should it be "as this is a random..."?

Take-them-or-leave-them other suggestions/notes:
- p4 second column, top, regarding important waters, I wonder whether you should note that water equilibration timescales can be substantial (because otherwise, removing the waters would be no problem -- they could just "find their homes" quickly and then you'd be good).
- p4 second column discussion of pdb2gmx, perhaps note that it isn't going to be able to recognize ligands, etc. (and reference protein-ligand tutorial where this comes up)
- in discussion of include files (p5 second column bottom) I wonder whether it's worth noting (footnote?) that include files can impact portability; I used to get people e-mailing me topology files and asking me to help them troubleshoot things, but they would forget to send their "include" files that I needed to be able to assess what was going on.
- p6 column 2 there is a note regarding SI units; I THINK SI units formally would mean "meters" so the remark that SI implies nanometers rather than angstroms is perhaps misplaced...? 
- p8 is there an option to genion that allows specifying a desired ionic strength
- p10 column 2 near bottom seems to suggest that simulated annealing and slowly warming the system are the same thing; this is not my understanding.

I regret that I ran out of time to read rather than skim after around p20-30 so suggestions after that point are sparse (though I checked some things that I have some expertise in and found them treated well). But hopefully this is worthwhile anyway.

**Comment by jalemkul** [comment]
Thanks @davidlmobley for the comments. I've addressed them in the latest version that I pushed a couple of days ago.
