### ISSUE TITLE
Paragraph breaks after lstlisting environment

### ISSUE THREAD

**Issue by dwsideriusNIST** [jalemkul/gmx_tutorials_livecoms#4]
Please check all instances of the {lstlisting} environment to determine if a paragraph break is intended after the {lstlisting} block.

If a paragraph break is not intended, replace the blank line following \end{lstlisting} with %. A LaTeX "good practice" is to precede and follow an environment like {lstlisting} with %s to prevent accidental paragraph break.

**Comment by jalemkul** [comment]
Thanks for the tip - I have reviewed the current version (from your PR) and all paragraph breaks are intended.

**Comment by dwsideriusNIST** [comment]
If all paragraph breaks are intended, then we have to deal some text structure issues.

First example; (current PDF in your repo), page 5 left column immediately after the code block. I would argue that the sentence/paragraph beginning "The first prompt ..." should not be a paragraph break because 1) it flows directly from the previous sentence/code block and 2) if actually intended, the previous paragraph would only have one sentence.

Second example; page 6 right column immediately after the code block. Same issue as before, though the previous paragraph would be OK in terms of sentence count. I think that "Doing so will..." follows directly from the code block and should not be a new paragraph.

I can come up with many similar instances, preferring that you handle them yourself to preserve textual intent.

**Comment by jalemkul** [comment]
OK, that makes sense. When the editors have agreed on the other style issues that we've discussed, I will merge in what I need from your PR and address these textual issues as well, hopefully giving the final version. Thanks for your attention to these details!

**Comment by jalemkul** [comment]
I merged your PR and have now pushed additional changes that correct the unnecessary paragraph breaks around the {lstlsting} and {equation} environments that were in the middle of continuous text. The change was applied to most of the instances of command-line examples, though not all, as some paragraphs were (at least in my reading) actually new paragraphs.

**Comment by dwsideriusNIST** [comment]
Closed following PR #5
