### ISSUE TITLE
Adding publication dates

### ISSUE THREAD

**Issue by dwsideriusNIST** [jalemkul/gmx_tutorials_livecoms#6]
Last update from my POV to prepare the manuscript for ASAP status:

Replace "Month, Day, Year" with the appropriate dates in these macros:

\datereceived{Month, Day, Year}
\dateaccepted{Month, Day, Year}

**Comment by jalemkul** [comment]
Should I expect this update to come from the editorial side, along with a DOI?

**Comment by dwsideriusNIST** [comment]
1. DOIs are on hold right now, pending some work done by the Managing Editors
2. The workflow for entering the received and accepted dates is still being developed. I think you can look up the received date based on emails from Scholastica. Same for the accepted date, once the paper is actually accepted.

**Comment by jalemkul** [comment]
OK, got it. I'll fill out the dates and push the update.
