### ISSUE TITLE
Test cases

### ISSUE THREAD

**Issue by bkmgit** [jalemkul/gmx_tutorials_livecoms#7]
These are really helpful. It would be nice to have small test cases that run in a few minutes on a low power dual core CPU. May also be worth indicating typical execution time for mdrun steps.

**Comment by jalemkul** [comment]
Hi,

I'm sorry I never saw this issue get raised - GitHub did not notify me about it at all.

What kind of test cases would you like to see? GROMACS has its own set of tests for integrity of the software; those prove that things are functioning in a far more comprehensive way than anything my tutorials would do.

Execution times are a bit beyond the scope of what I try to do with these tutorials, and vary so widely depending on available hardware and what type of compilation flags people use.

**Comment by bkmgit** [comment]
Will see if can create smaller test cases. Some of them require a reasonably powerful GPU, which may not be appropriate to use for a first tutorial.

People doing the tutorials could contribute information on how long they take to run, for example through a github pull request or similar. 

Collection of performance information could also be automated for the integrity tests, though not sure many people would be comfortable with automated upload of performance information. These may be less useful for the typical user since the typical user will not examine all the results reported by an integrity test.

**Comment by UnixJunkie** [comment]
My experience so far:
the production run for lysozyme in water took ~40 min on 24 threads.
The same on 12 threads plus a GPU took ~3min.
