### ISSUE TITLE
error on NPT step with freeze atoms

### ISSUE THREAD

**Issue by amarye** [jalemkul/gmx_tutorials_livecoms#8]
I wanna do MD simulation of a complex system. I did all steps till the NVT step with freeze ligand atoms, but when NPT ran I got an error:

Step 0  Warning: pressure scaling more than 1%, mu: 1.04917e+20 1.04917e+20 1.04917e+20 

I do not know why??? so I need your help?

**Comment by UnixJunkie** [comment]
Ask your question in the gromacs user community forum:
https://gromacs.bioexcel.eu/

**Comment by UnixJunkie** [comment]
This issue can probably be closed.
