### ISSUE TITLE
Gromacs 16 tutorials

### ISSUE THREAD

**Issue by darthgera123** [jalemkul/gmx_tutorials_livecoms#9]
Hi sorry for the weird request, but can you point me to gromacs16 tutorials since on my lab system that is setup and for some weird reasons i cant upgrade

**Comment by UnixJunkie** [comment]
Maybe install gromacs from sources in your user-space. Then you could use whatever gromacs version your want.

**Comment by UnixJunkie** [comment]
This issue can probably be closed.
